In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv('bds2018.csv')
df.head()

year    firms   estabs       emp     denom  estabs_entry  \
0  1978  3556792  4309087  69343368  66751651        653248   
1  1979  3669291  4448833  73334025  71221069        625171   
2  1980  3680090  4490716  73753303  73559310        581431   
3  1981  3731587  4573076  74381166  73983265        576302   
4  1982  3719903  4596342  74692330  74463460        598866   

   estabs_entry_rate  estabs_exit  estabs_exit_rate  job_creation  ...  \
0             15.458       487051            11.525      14661850  ...   
1             14.340       446657            10.245      13877812  ...   
2             13.068       498221            11.198      12088588  ...   
3             12.776       451584            10.011      11952898  ...   
4             13.130       528277            11.582      12666062  ...   

   job_destruction_deaths  job_destruction_continuers  \
0                 4064364                     5417039   
1                 3628922                     6018654   
2                 3746094                     7946658   
3                 3296935                     7851917   
4                 3729605                     8476201   

   job_destruction_rate_deaths  job_destruction_rate  net_job_creation  \
0                        6.089                14.204           5180447   
1                        5.095                13.546           4230236   
2                        5.093                15.896            395836   
3                        4.456                15.069            804046   
4                        5.009                16.392            460256   

   net_job_creation_rate  reallocation_rate  firmdeath_firms  \
0                  7.761             28.408           327133   
1                  5.940             27.092           299501   
2                  0.538             31.791           346328   
3                  1.087             30.139           296080   
4                  0.618             32.783           364758   

   firmdeath_estabs  firmdeath_emp  
0            332430        1825561  
1            304149        1674881  
2            352230        1918265  
3            302652        1546778  
4            371526        1921834  

[5 rows x 25 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   year                         41 non-null     int64  
 1   firms                        41 non-null     int64  
 2   estabs                       41 non-null     int64  
 3   emp                          41 non-null     int64  
 4   denom                        41 non-null     int64  
 5   estabs_entry                 41 non-null     int64  
 6   estabs_entry_rate            41 non-null     float64
 7   estabs_exit                  41 non-null     int64  
 8   estabs_exit_rate             41 non-null     float64
 9   job_creation                 41 non-null     int64  
 10  job_creation_births          41 non-null     int64  
 11  job_creation_continuers      41 non-null     int64  
 12  job_creation_rate_births     41 non-null     float64
 13  job_creation_rate     

In [8]:
df.describe().T

count          mean           std           min  \
year                          41.0  1.998000e+03  1.197915e+01  1.978000e+03   
firms                         41.0  4.647857e+06  5.353502e+05  3.556792e+06   
estabs                        41.0  5.967512e+06  8.579296e+05  4.309087e+06   
emp                           41.0  1.016854e+08  1.771518e+07  6.934337e+07   
denom                         41.0  1.008328e+08  1.793145e+07  6.675165e+07   
estabs_entry                  41.0  6.897798e+05  5.711593e+04  5.763020e+05   
estabs_entry_rate             41.0  1.187180e+01  1.687099e+00  9.145000e+00   
estabs_exit                   41.0  5.875324e+05  7.784804e+04  4.346700e+05   
estabs_exit_rate              41.0  9.991976e+00  8.270971e-01  8.099000e+00   
job_creation                  41.0  1.582376e+07  1.843843e+06  1.195290e+07   
job_creation_births           41.0  5.618704e+06  7.236357e+05  4.518780e+06   
job_creation_continuers       41.0  1.020505e+07  1.359745e+06  7.289159e+06   
job_creation_rate_births      41.0  5.738220e+00  1.152994e+00  3.903000e+00   
job_creation_rate             41.0  1.601646e+01  2.363230e+00  1.143400e+01   
job_destruction               41.0  1.412019e+07  2.464782e+06  9.481403e+06   
job_destruction_deaths        41.0  4.701214e+06  8.351744e+05  3.168837e+06   
job_destruction_continuers    41.0  9.418977e+06  1.748993e+06  5.417039e+06   
job_destruction_rate_deaths   41.0  4.730171e+00  7.511737e-01  3.352000e+00   
job_destruction_rate          41.0  1.416398e+01  1.952431e+00  1.071500e+01   
net_job_creation              41.0  1.703564e+06  2.175578e+06 -6.148679e+06   
net_job_creation_rate         41.0  1.852561e+00  2.371678e+00 -5.272000e+00   
reallocation_rate             41.0  2.774222e+01  3.584471e+00  2.143100e+01   
firmdeath_firms               41.0  3.894739e+05  4.417555e+04  2.933860e+05   
firmdeath_estabs              41.0  4.003117e+05  4.622401e+04  3.001610e+05   
firmdeath_emp                 41.0  2.402033e+06  4.063350e+05  1.546778e+06   

                                      25%           50%           75%  \
year                         1.988000e+03  1.998000e+03  2.008000e+03   
firms                        4.309957e+06  4.856029e+06  5.078400e+06   
estabs                       5.361852e+06  6.183518e+06  6.710119e+06   
emp                          8.836194e+07  1.075412e+08  1.151806e+08   
denom                        8.691060e+07  1.059296e+08  1.147239e+08   
estabs_entry                 6.552140e+05  6.935530e+05  7.105820e+05   
estabs_entry_rate            1.023300e+01  1.174000e+01  1.306800e+01   
estabs_exit                  5.438410e+05  5.881630e+05  6.332490e+05   
estabs_exit_rate             9.640000e+00  1.004200e+01  1.039900e+01   
job_creation                 1.495613e+07  1.576333e+07  1.698772e+07   
job_creation_births          5.018114e+06  5.594873e+06  6.156873e+06   
job_creation_continuers      9.598318e+06  1.030328e+07  1.134996e+07   
job_creation_rate_births     4.624000e+00  5.859000e+00  6.546000e+00   
job_creation_rate            1.412300e+01  1.632000e+01  1.701000e+01   
job_destruction              1.279894e+07  1.361400e+07  1.561836e+07   
job_destruction_deaths       4.109989e+06  4.558912e+06  5.271775e+06   
job_destruction_continuers   8.519684e+06  9.234787e+06  1.003478e+07   
job_destruction_rate_deaths  4.368000e+00  4.912000e+00  5.095000e+00   
job_destruction_rate         1.302400e+01  1.423500e+01  1.515800e+01   
net_job_creation             7.978100e+05  2.200059e+06  2.906197e+06   
net_job_creation_rate        7.650000e-01  1.986000e+00  2.924000e+00   
reallocation_rate            2.542000e+01  2.824700e+01  3.013900e+01   
firmdeath_firms              3.737600e+05  3.894110e+05  4.070990e+05   
firmdeath_estabs             3.821920e+05  4.027690e+05  4.191160e+05   
firmdeath_emp                2.136461e+06  2.490647e+06  2.606510e+06   

                                      max  
year 

In [11]:
bds_data=df.drop(['estabs_entry_rate','estabs_exit_rate','job_creation_births','job_creation_continuers','job_creation_rate_births',
             'job_destruction_deaths','job_destruction_continuers','job_destruction_rate_deaths','net_job_creation_rate',
             'firmdeath_emp','firmdeath_estabs','firmdeath_firms'],axis=1)

In [13]:
bds_data.head()

year    firms   estabs       emp     denom  estabs_entry  estabs_exit  \
0  1978  3556792  4309087  69343368  66751651        653248       487051   
1  1979  3669291  4448833  73334025  71221069        625171       446657   
2  1980  3680090  4490716  73753303  73559310        581431       498221   
3  1981  3731587  4573076  74381166  73983265        576302       451584   
4  1982  3719903  4596342  74692330  74463460        598866       528277   

   job_creation  job_creation_rate  job_destruction  job_destruction_rate  \
0      14661850             21.965          9481403                14.204   
1      13877812             19.486          9647576                13.546   
2      12088588             16.434         11692752                15.896   
3      11952898             16.156         11148852                15.069   
4      12666062             17.010         12205806                16.392   

   net_job_creation  reallocation_rate  
0           5180447             28.408  
1           4230236             27.092  
2            395836             31.791  
3            804046             30.139  
4            460256             32.783

In [14]:
bds_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   year                  41 non-null     int64  
 1   firms                 41 non-null     int64  
 2   estabs                41 non-null     int64  
 3   emp                   41 non-null     int64  
 4   denom                 41 non-null     int64  
 5   estabs_entry          41 non-null     int64  
 6   estabs_exit           41 non-null     int64  
 7   job_creation          41 non-null     int64  
 8   job_creation_rate     41 non-null     float64
 9   job_destruction       41 non-null     int64  
 10  job_destruction_rate  41 non-null     float64
 11  net_job_creation      41 non-null     int64  
 12  reallocation_rate     41 non-null     float64
dtypes: float64(3), int64(10)
memory usage: 4.3 KB


In [16]:
bds_data.describe().T

count          mean           std           min  \
year                   41.0  1.998000e+03  1.197915e+01  1.978000e+03   
firms                  41.0  4.647857e+06  5.353502e+05  3.556792e+06   
estabs                 41.0  5.967512e+06  8.579296e+05  4.309087e+06   
emp                    41.0  1.016854e+08  1.771518e+07  6.934337e+07   
denom                  41.0  1.008328e+08  1.793145e+07  6.675165e+07   
estabs_entry           41.0  6.897798e+05  5.711593e+04  5.763020e+05   
estabs_exit            41.0  5.875324e+05  7.784804e+04  4.346700e+05   
job_creation           41.0  1.582376e+07  1.843843e+06  1.195290e+07   
job_creation_rate      41.0  1.601646e+01  2.363230e+00  1.143400e+01   
job_destruction        41.0  1.412019e+07  2.464782e+06  9.481403e+06   
job_destruction_rate   41.0  1.416398e+01  1.952431e+00  1.071500e+01   
net_job_creation       41.0  1.703564e+06  2.175578e+06 -6.148679e+06   
reallocation_rate      41.0  2.774222e+01  3.584471e+00  2.143100e+01   

                               25%           50%           75%           max  
year                  1.988000e+03  1.998000e+03  2.008000e+03  2.018000e+03  
firms                 4.309957e+06  4.856029e+06  5.078400e+06  5.294414e+06  
estabs                5.361852e+06  6.183518e+06  6.710119e+06  7.097130e+06  
emp                   8.836194e+07  1.075412e+08  1.151806e+08  1.298406e+08  
denom                 8.691060e+07  1.059296e+08  1.147239e+08  1.285678e+08  
estabs_entry          6.552140e+05  6.935530e+05  7.105820e+05  8.724250e+05  
estabs_exit           5.438410e+05  5.881630e+05  6.332490e+05  7.744780e+05  
job_creation          1.495613e+07  1.576333e+07  1.698772e+07  1.888156e+07  
job_creation_rate     1.412300e+01  1.632000e+01  1.701000e+01  2.196500e+01  
job_destruction       1.279894e+07  1.361400e+07  1.561836e+07  2.151826e+07  
job_destruction_rate  1.302400e+01  1.423500e+01  1.515800e+01  1.901600e+01  
net_job_creation      7.978100e+05  2.200059e+06  2.906197e+06  5.373327e+06  
reallocation_rate     2.542000e+01  2.824700e+01  3.013900e+01  3.458300e+01

# DATA PROCESSING

1. BINARIZATION 
2. SCALING 
3.NORMALIZATION 
4.MEAN REMOVAL

In [73]:
from sklearn import preprocessing

In [74]:
#BINARIZATION
bds_binarized=preprocessing.Binarizer(threshold=0.5).transform(bds_data)
bds_binarized

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 

In [75]:
# MEAN REMOVAL
print('Mean=',bds_data.mean(axis=0))
      
print('Std_devetion',bds_data.std(axis=0))

Mean= [1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         0.85365854
 1.        ]
Std_devetion [0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.35344821
 0.        ]


In [76]:
bds_scaled=preprocessing.scale(bds_data)
print('Mean=',bds_scaled.mean(axis=0))
print('Std=',bds_scaled.std(axis=0))

Mean= [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 9.47751362e-18
 0.00000000e+00]
Std= [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


In [77]:
# SCALING. Transform feature vectors between (0,1)

data_scaler_minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax=data_scaler_minmax.fit_transform(bds_data)
data_scaled_minmax

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 

In [78]:
#NORMALIZATION 
# L1_Normalization.(Least Absolute Deviations). Sum of absolute values targeted to be upto 1.

data_normalized_l1=preprocessing.normalize(bds_data,norm='l1')
print('L1 Normalized'
      ,data_normalized_l1)

L1 Normalized [[0.07692308 0.07692308 0.07692308 0.07692308 0.07692308 0.07692308
  0.07692308 0.07692308 0.07692308 0.07692308 0.07692308 0.07692308
  0.07692308]
 [0.07692308 0.07692308 0.07692308 0.07692308 0.07692308 0.07692308
  0.07692308 0.07692308 0.07692308 0.07692308 0.07692308 0.07692308
  0.07692308]
 [0.07692308 0.07692308 0.07692308 0.07692308 0.07692308 0.07692308
  0.07692308 0.07692308 0.07692308 0.07692308 0.07692308 0.07692308
  0.07692308]
 [0.07692308 0.07692308 0.07692308 0.07692308 0.07692308 0.07692308
  0.07692308 0.07692308 0.07692308 0.07692308 0.07692308 0.07692308
  0.07692308]
 [0.07692308 0.07692308 0.07692308 0.07692308 0.07692308 0.07692308
  0.07692308 0.07692308 0.07692308 0.07692308 0.07692308 0.07692308
  0.07692308]
 [0.08333333 0.08333333 0.08333333 0.08333333 0.08333333 0.08333333
  0.08333333 0.08333333 0.08333333 0.08333333 0.08333333 0.
  0.08333333]
 [0.07692308 0.07692308 0.07692308 0.07692308 0.07692308 0.07692308
  0.07692308 0.07692308 0.

In [79]:
#L2 Normalization(Least Squares). Modifies values such that sum of squares is always up to 1 in each row.
data_normalized_l2=preprocessing.normalize(bds_data, norm='l2')
print('data_normalize_l2',data_normalized_l2)

data_normalize_l2 [[0.2773501  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501
  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501
  0.2773501 ]
 [0.2773501  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501
  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501
  0.2773501 ]
 [0.2773501  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501
  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501
  0.2773501 ]
 [0.2773501  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501
  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501
  0.2773501 ]
 [0.2773501  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501
  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501
  0.2773501 ]
 [0.28867513 0.28867513 0.28867513 0.28867513 0.28867513 0.28867513
  0.28867513 0.28867513 0.28867513 0.28867513 0.28867513 0.
  0.28867513]
 [0.2773501  0.2773501  0.2773501  0.2773501  0.2773501  0.2773501
  0.2773501  0.2773501  0.2773501

In [80]:
copies=60
b_1=24.95  # Initial price
b_1d=b_1*60/100   #new price after getting a discount
print("Price after discount= $",b_1d)
s_1=3   # Shipping fee of the first copy
s_1a=s_1+((copies-1)*3*75/100)  # Shipping fee of the first copy + additional copies
print("Total shipping fee= $",s_1a)
T_C=(copies*b_1d)+s_1a   # Total wholesale amount
print("Total cost= $",T_C)

Price after discount= $ 14.97
Total shipping fee= $ 135.75
Total cost= $ 1033.95


# LABELING THE DATA
- Transforming word labels to numerical form

In [89]:
from sklearn import preprocessing
import numpy as np
Sample_data=['prince','salome','kiiria','yellow','blue','green','uber','v8']

In [90]:
#creating the encoder
encoder=preprocessing.LabelEncoder()
encoder.fit(Sample_data)

LabelEncoder()

In [95]:
#checking performance on new data.
Test_sample=['blue','v8','green','uber']
encoded_values=encoder.transform(Test_sample)
encoded_values

array([0, 6, 1, 5])

In [106]:
# Checking perfomance by decoding values.
encoded_values=[7,0,2,1,4,6,3,7]
decoder_values=encoder.inverse_transform(encoded_values)
decoder_values

array(['yellow', 'blue', 'kiiria', 'green', 'salome', 'v8', 'prince',
       'yellow'], dtype='<U6')

In [107]:
bds_data

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 

In [27]:
# Classification Algorithm
import pandas as pd
import numpy as np
df=pd.read_csv('covid data.csv')
df

dateRep  day  month  year  cases  deaths countriesAndTerritories  \
0      14/12/2020   14     12  2020    746       6             Afghanistan   
1      13/12/2020   13     12  2020    298       9             Afghanistan   
2      12/12/2020   12     12  2020    113      11             Afghanistan   
3      11/12/2020   11     12  2020     63      10             Afghanistan   
4      10/12/2020   10     12  2020    202      16             Afghanistan   
...           ...  ...    ...   ...    ...     ...                     ...   
61895  25/03/2020   25      3  2020      0       0                Zimbabwe   
61896  24/03/2020   24      3  2020      0       1                Zimbabwe   
61897  23/03/2020   23      3  2020      0       0                Zimbabwe   
61898  22/03/2020   22      3  2020      1       0                Zimbabwe   
61899  21/03/2020   21      3  2020      1       0                Zimbabwe   

      geoId countryterritoryCode  popData2019 continentExp  \
0        AF                  AFG   38041757.0         Asia   
1        AF                  AFG   38041757.0         Asia   
2        AF                  AFG   38041757.0         Asia   
3        AF                  AFG   38041757.0         Asia   
4        AF                  AFG   38041757.0         Asia   
...     ...                  ...          ...          ...   
61895    ZW                  ZWE   14645473.0       Africa   
61896    ZW                  ZWE   14645473.0       Africa   
61897    ZW                  ZWE   14645473.0       Africa   
61898    ZW                  ZWE   14645473.0       Africa   
61899    ZW                  ZWE   14645473.0       Africa   

       Cumulative_number_for_14_days_of_COVID-19_cases_per_100000  
0                                               9.013779           
1                                               7.052776           
2                                               6.868768           
3                                               7.134266           
4                                               6.968658           
...                                                  ...           
61895                                                NaN           
61896                                                NaN           
61897                                                NaN           
61898                                                NaN           
61899                                                NaN           

[61900 rows x 12 columns]

In [28]:
colm_Extract=df.countriesAndTerritories
colm_Extract

0        Afghanistan
1        Afghanistan
2        Afghanistan
3        Afghanistan
4        Afghanistan
            ...     
61895       Zimbabwe
61896       Zimbabwe
61897       Zimbabwe
61898       Zimbabwe
61899       Zimbabwe
Name: countriesAndTerritories, Length: 61900, dtype: object

In [29]:
from sklearn import preprocessing
encoder=preprocessing.LabelEncoder()
encoder=encoder.fit(colm_Extract)
encoder

LabelEncoder()

In [30]:
Test_sample=['Afghanistan','Kenya','Zambia','Uganda','Togo','Egypt']
encoder_test=encoder.transform(Test_sample)
encoder_test

array([  0, 105, 212, 197, 192,  59])

In [31]:
Values=[105,212,197,192,95,59,98,58,0,1,2,3,4,5]
decoder_value=encoder.inverse_transform(Values)
decoder_value

array(['Kenya', 'Zambia', 'Uganda', 'Togo', 'Iraq', 'Egypt', 'Israel',
       'Ecuador', 'Afghanistan', 'Albania', 'Algeria', 'Andorra',
       'Angola', 'Anguilla'], dtype=object)

In [32]:
df.isnull().sum()

dateRep                                                          0
day                                                              0
month                                                            0
year                                                             0
cases                                                            0
deaths                                                           0
countriesAndTerritories                                          0
geoId                                                          275
countryterritoryCode                                           123
popData2019                                                    123
continentExp                                                     0
Cumulative_number_for_14_days_of_COVID-19_cases_per_100000    2879
dtype: int64

In [33]:
covid_data=df.drop(['dateRep','countriesAndTerritories','geoId','countryterritoryCode','continentExp'],axis=1)

In [34]:
covid_data.head()

day  month  year  cases  deaths  popData2019  \
0   14     12  2020    746       6   38041757.0   
1   13     12  2020    298       9   38041757.0   
2   12     12  2020    113      11   38041757.0   
3   11     12  2020     63      10   38041757.0   
4   10     12  2020    202      16   38041757.0   

   Cumulative_number_for_14_days_of_COVID-19_cases_per_100000  
0                                           9.013779           
1                                           7.052776           
2                                           6.868768           
3                                           7.134266           
4                                           6.968658

In [35]:
covid_data.drop('Cumulative_number_for_14_days_of_COVID-19_cases_per_100000',axis=1,inplace=True)
covid_data

day  month  year  cases  deaths  popData2019
0       14     12  2020    746       6   38041757.0
1       13     12  2020    298       9   38041757.0
2       12     12  2020    113      11   38041757.0
3       11     12  2020     63      10   38041757.0
4       10     12  2020    202      16   38041757.0
...    ...    ...   ...    ...     ...          ...
61895   25      3  2020      0       0   14645473.0
61896   24      3  2020      0       1   14645473.0
61897   23      3  2020      0       0   14645473.0
61898   22      3  2020      1       0   14645473.0
61899   21      3  2020      1       0   14645473.0

[61900 rows x 6 columns]

In [36]:
covid_data.popData2019.fillna(0,inplace=True)

In [37]:
X=covid_data.drop('cases',axis=1)
y=covid_data['cases']

In [62]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [63]:
X_test

day  month  year  deaths  popData2019
19065    4      8  2020      52  112078727.0
503      4      7  2020       3    2862427.0
11254    3      4  2020       0      64948.0
54144   12      6  2020      35   10230185.0
39649   22      9  2020       1    2494524.0
...    ...    ...   ...     ...          ...
60056    2      7  2020       0   32981715.0
52234   22      8  2020       0   51225321.0
46268    1     11  2020       0    2832071.0
34463    7      8  2020       1     613894.0
61155   31     10  2020       0   29161922.0

[12380 rows x 5 columns]

In [64]:
X_train

day  month  year  deaths  popData2019
35914   22      9  2020       0   19658023.0
2005    26      4  2020       0      97115.0
12941   14      5  2020       0     850891.0
29300   27      5  2020      78   60359546.0
28606   13      8  2020       0      84589.0
...    ...    ...   ...     ...          ...
45891   13      5  2020      19   10276617.0
52416   22      2  2020       1   51225321.0
42613    3      4  2020       0      57213.0
43567    2      4  2020       5  216565317.0
2732    10     10  2020       1     106310.0

[49520 rows x 5 columns]

In [65]:
from sklearn.naive_bayes import GaussianNB  #import model
gnb=GaussianNB()   #Initioalize model

In [66]:
model=gnb.fit(X_train,y_train)

In [67]:
y_test

19065    1290
503        90
11254       6
54144    1293
39649     149
         ... 
60056     277
52234     332
46268     213
34463      66
61155       0
Name: cases, Length: 12380, dtype: int64

In [68]:
y_test#=covid_data['cases']

19065    1290
503        90
11254       6
54144    1293
39649     149
         ... 
60056     277
52234     332
46268     213
34463      66
61155       0
Name: cases, Length: 12380, dtype: int64

In [75]:
y_pred=gnb.predict(X_test)
y_pred

array([1460,    0,    0, ..., 1830,    0,    0], dtype=int64)

In [70]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.23513731825525042

In [71]:
y_preds=[[6,12,2021,576,458667],
        [7,2,2022,586,543235]]

In [72]:
y_pred=gnb.predict(y_preds)
y_pred

array([0, 0], dtype=int64)